In [1]:
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [2]:
df = pd.read_csv(r"C:\Users\mehul\OneDrive\Documents\datasets\oasis_longitudinal.csv")
df.head()

Subject ID         MRI ID        Group  Visit  MR Delay M/F Hand  Age  EDUC  \
0  OAS2_0001  OAS2_0001_MR1  Nondemented      1         0   M    R   87    14   
1  OAS2_0001  OAS2_0001_MR2  Nondemented      2       457   M    R   88    14   
2  OAS2_0002  OAS2_0002_MR1     Demented      1         0   M    R   75    12   
3  OAS2_0002  OAS2_0002_MR2     Demented      2       560   M    R   76    12   
4  OAS2_0002  OAS2_0002_MR3     Demented      3      1895   M    R   80    12   

   SES  MMSE  CDR  eTIV   nWBV    ASF  
0  2.0  27.0  0.0  1987  0.696  0.883  
1  2.0  30.0  0.0  2004  0.681  0.876  
2  NaN  23.0  0.5  1678  0.736  1.046  
3  NaN  28.0  0.5  1738  0.713  1.010  
4  NaN  22.0  0.5  1698  0.701  1.034

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Subject ID  373 non-null    object 
 1   MRI ID      373 non-null    object 
 2   Group       373 non-null    object 
 3   Visit       373 non-null    int64  
 4   MR Delay    373 non-null    int64  
 5   M/F         373 non-null    object 
 6   Hand        373 non-null    object 
 7   Age         373 non-null    int64  
 8   EDUC        373 non-null    int64  
 9   SES         354 non-null    float64
 10  MMSE        371 non-null    float64
 11  CDR         373 non-null    float64
 12  eTIV        373 non-null    int64  
 13  nWBV        373 non-null    float64
 14  ASF         373 non-null    float64
dtypes: float64(5), int64(5), object(5)
memory usage: 43.8+ KB


In [4]:
df.shape

(373, 15)

In [5]:
df.describe()

Visit     MR Delay         Age        EDUC         SES  \
count  373.000000   373.000000  373.000000  373.000000  354.000000   
mean     1.882038   595.104558   77.013405   14.597855    2.460452   
std      0.922843   635.485118    7.640957    2.876339    1.134005   
min      1.000000     0.000000   60.000000    6.000000    1.000000   
25%      1.000000     0.000000   71.000000   12.000000    2.000000   
50%      2.000000   552.000000   77.000000   15.000000    2.000000   
75%      2.000000   873.000000   82.000000   16.000000    3.000000   
max      5.000000  2639.000000   98.000000   23.000000    5.000000   

             MMSE         CDR         eTIV        nWBV         ASF  
count  371.000000  373.000000   373.000000  373.000000  373.000000  
mean    27.342318    0.290885  1488.128686    0.729568    1.195461  
std      3.683244    0.374557   176.139286    0.037135    0.138092  
min      4.000000    0.000000  1106.000000    0.644000    0.876000  
25%     27.000000    0.000000  1357.000000    0.700000    1.099000  
50%     29.000000    0.000000  1470.000000    0.729000    1.194000  
75%     30.000000    0.500000  1597.000000    0.756000    1.293000  
max     30.000000    2.000000  2004.000000    0.837000    1.587000

In [6]:
df.corr()

Visit  MR Delay       Age      EDUC       SES      MMSE  \
Visit     1.000000  0.920009  0.183213  0.024615 -0.051622 -0.029078   
MR Delay  0.920009  1.000000  0.205357  0.051630 -0.030813  0.065844   
Age       0.183213  0.205357  1.000000 -0.027886 -0.046857  0.055612   
EDUC      0.024615  0.051630 -0.027886  1.000000 -0.722647  0.194884   
SES      -0.051622 -0.030813 -0.046857 -0.722647  1.000000 -0.149219   
MMSE     -0.029078  0.065844  0.055612  0.194884 -0.149219  1.000000   
CDR       0.002325 -0.062915 -0.026257 -0.153121  0.076160 -0.686519   
eTIV      0.117428  0.119624  0.042348  0.257015 -0.261575 -0.032084   
nWBV     -0.126682 -0.105586 -0.518359 -0.012200  0.090095  0.341912   
ASF      -0.120399 -0.123545 -0.035067 -0.241752  0.255576  0.040052   

               CDR      eTIV      nWBV       ASF  
Visit     0.002325  0.117428 -0.126682 -0.120399  
MR Delay -0.062915  0.119624 -0.105586 -0.123545  
Age      -0.026257  0.042348 -0.518359 -0.035067  
EDUC     -0.153121  0.257015 -0.012200 -0.241752  
SES       0.076160 -0.261575  0.090095  0.255576  
MMSE     -0.686519 -0.032084  0.341912  0.040052  
CDR       1.000000  0.022819 -0.344819 -0.029340  
eTIV      0.022819  1.000000 -0.210122 -0.988877  
nWBV     -0.344819 -0.210122  1.000000  0.213476  
ASF      -0.029340 -0.988877  0.213476  1.000000

In [7]:
df['Group'].replace(['Nondemented','Demented','Converted'],[0,1,2],inplace = True)
df['M/F'].replace(['M','F'],[0,1],inplace = True)
df.drop(["Hand","Subject ID","MRI ID"],axis=1,inplace=True)

def impute_median(series):
    return series.fillna(series.median())

df["SES"]= df["SES"].transform(impute_median)
df["MMSE"]= df["MMSE"].transform(impute_median)
df.head(5)

Group  Visit  MR Delay  M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0      0      1         0    0   87    14  2.0  27.0  0.0  1987  0.696  0.883
1      0      2       457    0   88    14  2.0  30.0  0.0  2004  0.681  0.876
2      1      1         0    0   75    12  2.0  23.0  0.5  1678  0.736  1.046
3      1      2       560    0   76    12  2.0  28.0  0.5  1738  0.713  1.010
4      1      3      1895    0   80    12  2.0  22.0  0.5  1698  0.701  1.034

In [8]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [9]:
X = df.iloc[:,1:11]
Y = df.iloc[:,2]

In [10]:
best_features= SelectKBest(score_func = chi2,k=3)
fit = best_features.fit(X,Y)

In [11]:
df_scores= pd.DataFrame(fit.scores_)
df_columns= pd.DataFrame(X.columns)

In [12]:
features_scores= pd.concat([df_columns, df_scores], axis=1)
features_scores.columns= ['Features', 'Score']
features_scores.sort_values(by = 'Score')

Features          Score
9      nWBV       0.405640
2       M/F      83.753897
5       SES     105.841768
7       CDR     108.418694
4      EDUC     111.706703
6      MMSE     123.060944
3       Age     160.496211
0     Visit     167.270655
8      eTIV    4340.081286
1  MR Delay  252441.314713

In [13]:
X= df[['nWBV', 'M/F', 'SES']]  
Y= df['Group']

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.4,random_state=100)

In [15]:
logreg= LogisticRegression()
logreg.fit(X_train,Y_train)

LogisticRegression()

In [16]:
y_pred=logreg.predict(X_test)
print (X_test) #test dataset
print (y_pred) #predicted values

      nWBV  M/F  SES
161  0.743    1  5.0
178  0.686    1  4.0
132  0.677    1  2.0
98   0.703    0  1.0
208  0.750    1  2.0
..     ...  ...  ...
123  0.707    0  3.0
160  0.769    1  3.0
159  0.774    1  3.0
61   0.676    0  3.0
71   0.778    1  4.0

[150 rows x 3 columns]
[0 0 0 1 0 1 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0 1
 0 1 0 0 0 1 0 1 1 0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 0 0 1
 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0
 1 0]


In [17]:
print('Train Score',logreg.score(X_train,Y_train))
print('Test Score',logreg.score(X_test,Y_test))

Train Score 0.5246636771300448
Test Score 0.6333333333333333


In [18]:
from sklearn import metrics
from sklearn.metrics import classification_report
print('Accuracy_1: ',metrics.accuracy_score(Y_test, y_pred))
print("Recall Score_1: ",metrics.recall_score(Y_test, y_pred, pos_label='positive',average='micro'))
print("Precision Score_1 : ",metrics.precision_score(Y_test, y_pred, pos_label='positive',average='micro'))
print('CL Report:',metrics.classification_report(Y_test, y_pred, zero_division=1))

Accuracy_1:  0.6333333333333333
Recall Score_1:  0.6333333333333333
Precision Score_1 :  0.6333333333333333
CL Report:               precision    recall  f1-score   support

           0       0.68      0.70      0.69        84
           1       0.57      0.60      0.59        60
           2       1.00      0.00      0.00         6

    accuracy                           0.63       150
   macro avg       0.75      0.43      0.43       150
weighted avg       0.65      0.63      0.62       150



C:\Users\mehul\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\mehul\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [19]:
from sklearn.svm import SVC

In [20]:
svm1 = SVC(kernel='linear',C=1)
svm1.fit(X_train,Y_train)

SVC(C=1, kernel='linear')

In [21]:
ypred = svm1.predict(X_test)
print(ypred)

[0 0 0 1 0 1 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 1
 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0 1
 0 1 0 0 0 1 0 1 1 0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 0 0 1
 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0
 1 0]


In [22]:
print('Train Score',svm1.score(X_train,Y_train))
print('Test Score',svm1.score(X_test,Y_test))

Train Score 0.5381165919282511
Test Score 0.6333333333333333


In [25]:
print('Accuracy_2: ',metrics.accuracy_score(Y_test, ypred))
print("Recall Score_2: ",metrics.recall_score(Y_test, ypred, pos_label='positive',average='micro'))
print("Precision Score_2 : ",metrics.precision_score(Y_test, ypred, pos_label='positive',average='micro'))
print('CL Report:',metrics.classification_report(Y_test, ypred, zero_division=1))

Accuracy_2:  0.6333333333333333
Recall Score_2:  0.6333333333333333
Precision Score_2 :  0.6333333333333333
CL Report:               precision    recall  f1-score   support

           0       0.68      0.69      0.69        84
           1       0.57      0.62      0.59        60
           2       1.00      0.00      0.00         6

    accuracy                           0.63       150
   macro avg       0.75      0.44      0.43       150
weighted avg       0.65      0.63      0.62       150



C:\Users\mehul\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\mehul\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
m1 = KNeighborsClassifier(n_neighbors=11)
m1.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=11)

In [29]:
y1pred_m1 = m1.predict(X_test)
print(y1pred_m1)

[1 0 1 1 0 0 0 1 1 1 0 1 1 0 2 0 0 0 2 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 2 1 1
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 1 0 0 0 0 1 0 0 1 0 1
 1 1 0 0 0 1 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1 1 1 1 1 0 0 0 2 1 0 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0
 1 0]


C:\Users\mehul\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [31]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test,y1pred_m1))
print(classification_report(Y_test,y1pred_m1))

[[61 23  0]
 [29 28  3]
 [ 3  2  1]]
              precision    recall  f1-score   support

           0       0.66      0.73      0.69        84
           1       0.53      0.47      0.50        60
           2       0.25      0.17      0.20         6

    accuracy                           0.60       150
   macro avg       0.48      0.45      0.46       150
weighted avg       0.59      0.60      0.59       150



In [34]:
print('Train Score',m1.score(X_train,Y_train)) # Accuracy
print('Test Score',m1.score(X_test,Y_test)) 

Train Score 0.600896860986547
Test Score 0.6


C:\Users\mehul\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\mehul\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim