In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk

from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn import metrics
from sklearn.metrics import confusion_matrix,classification_report

In [2]:
df = pd.read_csv('disaster_tweets_data.csv',encoding='latin1')
df.head()

tweets  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [3]:
df.columns = ['tweets','target']
df.head()

tweets  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [4]:
df['tweets'][11]

'Haha South Tampa is getting flooded hah- WAIT A SECOND I LIVE IN SOUTH TAMPA WHAT AM I GONNA DO WHAT AM I GONNA DO FVCK #flooding'

In [5]:
lm = WordNetLemmatizer()
sw = stopwords.words('English')
print(sw[:5])

['i', 'me', 'my', 'myself', 'we']


In [6]:
data = []
for i in df['tweets'].iloc[:5]:
    t = i.lower()                     # lower case conversion
    t = re.sub('[^A-Za-z0-9]',' ',t)  # removing punc
    t = word_tokenize(t)              # word tekenize
    t = [i for i in t if i not in sw] # sw removal
    t = [lm.lemmatize(i) for i in t]  # lemmatization
    t = " ".join(t)                   # joinig words to froms sentences
    data.append(t)
print(data)

['deed reason earthquake may allah forgive u', 'forest fire near la ronge sask canada', 'resident asked shelter place notified officer evacuation shelter place order expected', '13 000 people receive wildfire evacuation order california', 'got sent photo ruby alaska smoke wildfire pours school']


In [8]:
data = []
for i in df['tweets']:
    t = i.lower()                     # lower case conversion
    t = re.sub('[^A-Za-z0-9]',' ',t)  # removing punc
    t = word_tokenize(t)              # word tekenize
    t = [i for i in t if i not in sw] # sw removal
    t = [lm.lemmatize(i) for i in t]  # lemmatization
    t = " ".join(t)                   # joinig words to froms sentences
    data.append(t)
print(len(data))

7613


In [9]:
x = np.array(data)
y = df['target']

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=42)


In [11]:
cv = CountVectorizer(max_features=1500)

x_train_cv = cv.fit_transform(x_train)
x_test_cv = cv.transform(x_test)
print(x_train_cv.shape)
print(x_test_cv.shape)

(5329, 1500)
(2284, 1500)


In [22]:
def eval_model(ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    print('Accuracy: ',metrics.accuracy_score(y_test, ypred))
    print(cm)
    print(classification_report(ytest,ypred))

In [12]:
mnb = MultinomialNB()
mnb.fit(x_train_cv,y_train)

MultinomialNB()

In [13]:
print('Train Score',mnb.score(x_train_cv,y_train))  # Train Acc
print('Test Score',mnb.score(x_test_cv,y_test))

Train Score 0.8239819853631075
Test Score 0.7841506129597198


In [15]:
ypred_mnb = mnb.predict(x_test_cv)

In [16]:
lr = LogisticRegression()
lr.fit(x_train_cv,y_train)

C:\Users\mehul\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
print('Train Score',lr.score(x_train_cv,y_train))
print('Test Score',lr.score(x_test_cv,y_test))

Train Score 0.8799024207168324
Test Score 0.7981611208406305


In [18]:
ypred_lr = lr.predict(x_test_cv)

In [19]:
m1 = KNeighborsClassifier(n_neighbors=11)
m1.fit(x_train_cv,y_train)

KNeighborsClassifier(n_neighbors=11)

In [20]:
print('Train Score',m1.score(x_train_cv,y_train)) # Accuracy
print('Test Score',m1.score(x_test_cv,y_test))

C:\Users\mehul\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Train Score 0.7547382248076562
Test Score 0.7092819614711033


C:\Users\mehul\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [21]:
pred_m1 = m1.predict(x_test_cv)

C:\Users\mehul\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [29]:
print("FOR LOGISTIC REGRESSION :-")
eval_model(y_test,ypred_lr)

FOR LOGISTIC REGRESSION :-
Accuracy:  0.7981611208406305
[[1137  181]
 [ 280  686]]
              precision    recall  f1-score   support

           0       0.80      0.86      0.83      1318
           1       0.79      0.71      0.75       966

    accuracy                           0.80      2284
   macro avg       0.80      0.79      0.79      2284
weighted avg       0.80      0.80      0.80      2284



In [30]:
print("FOR Multinomial Naïve Bayes Classification  :-")
eval_model(y_test,ypred_mnb)

FOR Multinomial Naïve Bayes Classification  :-
Accuracy:  0.7841506129597198
[[1113  205]
 [ 288  678]]
              precision    recall  f1-score   support

           0       0.79      0.84      0.82      1318
           1       0.77      0.70      0.73       966

    accuracy                           0.78      2284
   macro avg       0.78      0.77      0.78      2284
weighted avg       0.78      0.78      0.78      2284



In [31]:
print("FOR KNN Classification :-")
eval_model(y_test,ypred_m1)

FOR KNN Classification :-
Accuracy:  0.7092819614711033
[[1226   92]
 [ 572  394]]
              precision    recall  f1-score   support

           0       0.68      0.93      0.79      1318
           1       0.81      0.41      0.54       966

    accuracy                           0.71      2284
   macro avg       0.75      0.67      0.66      2284
weighted avg       0.74      0.71      0.68      2284

