In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
df = pd.read_csv('mobile_price_range_data.csv')
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [3]:
df.shape

(2000, 21)

In [4]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
x = df.drop("price_range",axis = 1)
y = df["price_range"]
print(type(x))  # df
print(type(y))  # Series
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(2000, 20)
(2000,)


In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.22,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1560, 20)
(440, 20)
(1560,)
(440,)


In [8]:
sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)
print(x_train_sc.shape)
print(x_test_sc.shape)

(1560, 20)
(440, 20)


In [25]:
def eval_model(ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    print('Accuracy: ',metrics.accuracy_score(y_test, ypred))
    print(cm)
    print(classification_report(ytest,ypred))

In [9]:
lr = LogisticRegression()
lr.fit(x_train_sc,y_train)

LogisticRegression()

In [10]:
print('Train Score',lr.score(x_train_sc,y_train))
print('Test Score',lr.score(x_test_sc,y_test))

Train Score 0.9775641025641025
Test Score 0.9659090909090909


In [11]:
ypred_lr = lr.predict(x_test_sc)

In [52]:
svm1 = SVC(kernel='rbf',gamma=0.01)
svm1.fit(x_train_sc,y_train)

SVC(gamma=0.01)

In [53]:
ypred_svm1=svm1.predict(x_test_sc)

In [54]:
print('Train Score',svm1.score(x_train_sc,y_train))
print('Test Score',svm1.score(x_test_sc,y_test))

Train Score 0.9448717948717948
Test Score 0.9204545454545454


In [14]:
svm2 = SVC(kernel='linear')
svm2.fit(x_train_sc,y_train)

SVC(kernel='linear')

In [29]:
print('Train Score',svm2.score(x_train_sc,y_train))
print('Test Score',svm2.score(x_test_sc,y_test))

Train Score 0.9782051282051282
Test Score 0.9613636363636363


In [16]:
ypred_svm2 = svm2.predict(x_test_sc)

In [92]:
# K NEIGHBORS CLASSIFICATION

m1 = KNeighborsClassifier(n_neighbors=11)
m1.fit(x_train_sc,y_train)

KNeighborsClassifier(n_neighbors=11)

In [93]:
print('Train Score',m1.score(x_train_sc,y_train)) # Accuracy
print('Test Score',m1.score(x_test_sc,y_test))

Train Score 0.6717948717948717
Test Score 0.5590909090909091


C:\Users\mehul\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\mehul\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

In [94]:
ypred_m1 = m1.predict(x_test_sc)


C:\Users\mehul\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [88]:
print("FOR LOGISTIC REGRESSION :- \n")
eval_model(y_test,ypred_lr)

FOR LOGISTIC REGRESSION :- 

Accuracy:  0.9659090909090909
[[112   6   0   0]
 [  0 103   0   0]
 [  0   4  94   4]
 [  0   0   1 116]]
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       118
           1       0.91      1.00      0.95       103
           2       0.99      0.92      0.95       102
           3       0.97      0.99      0.98       117

    accuracy                           0.97       440
   macro avg       0.97      0.97      0.97       440
weighted avg       0.97      0.97      0.97       440



In [89]:
print("FOR SVM USING LINEAR KERNEL :- \n")
eval_model(y_test,ypred_svm2)

FOR SVM USING LINEAR KERNEL :- 

Accuracy:  0.9613636363636363
[[110   8   0   0]
 [  0 103   0   0]
 [  0   5  93   4]
 [  0   0   0 117]]
              precision    recall  f1-score   support

           0       1.00      0.93      0.96       118
           1       0.89      1.00      0.94       103
           2       1.00      0.91      0.95       102
           3       0.97      1.00      0.98       117

    accuracy                           0.96       440
   macro avg       0.96      0.96      0.96       440
weighted avg       0.96      0.96      0.96       440



In [90]:
print("FOR SVM USING RBF KERNEL :- \n")
eval_model(y_test,ypred_svm1)

FOR SVM USING RBF KERNEL :- 

Accuracy:  0.9204545454545454
[[113   5   0   0]
 [  1  97   5   0]
 [  0   8  89   5]
 [  0   0  11 106]]
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       118
           1       0.88      0.94      0.91       103
           2       0.85      0.87      0.86       102
           3       0.95      0.91      0.93       117

    accuracy                           0.92       440
   macro avg       0.92      0.92      0.92       440
weighted avg       0.92      0.92      0.92       440



In [95]:
print("FOR K NEIGHBORS CLASSIFIER :- \n")
eval_model(y_test,ypred_m1)

FOR K NEIGHBORS CLASSIFIER :- 

Accuracy:  0.5590909090909091
[[89 26  3  0]
 [35 41 21  6]
 [ 8 34 46 14]
 [ 1  6 40 70]]
              precision    recall  f1-score   support

           0       0.67      0.75      0.71       118
           1       0.38      0.40      0.39       103
           2       0.42      0.45      0.43       102
           3       0.78      0.60      0.68       117

    accuracy                           0.56       440
   macro avg       0.56      0.55      0.55       440
weighted avg       0.57      0.56      0.56       440



In [ ]:
### SO LOGISTIC REGRESSION HAS THE HIGHEST ACCURACY

